---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mirt)
mirtCluster()
library(rsample)
theme_set(theme_classic(base_size = 14))
options(pillar.sigfig = 6)

R.utils::sourceDirectory("~/Google_Drive/5_Projects/irt_comparison_folders/irt_comparison3/R")
source("archived/06_functions.R")

areas <- read_rds("data-clean/areas.rds")
d <- read_rds("data-clean/d.rds")
d_mat <- read_rds("data-clean/d_mat.rds")
item_area <- areas$area[match(colnames(d_mat), areas$paste)]

# filter out age == 1
ages <- 
    d %>% 
    group_by(id) %>% 
    summarize(age = age[1]) %>% 
    filter(age > 1)

d_mat <- d_mat[row.names(d_mat) %in% ages$id, ]
# end filter

splits_d_mat <- vfold_cv(d_mat, v = 5) # crank
```

# mirts 1 and 2 (or all actually)

```{r}
mirts <- 
  tribble(
    ~factors,  ~itemtype,
        "1",      "Rasch",
        "1",      "2PL",
        "2",      "2PL",
        "3",      "2PL",
        "4",      "2PL"    
  ) %>% 
    mutate(
        model_full =
            map2(
                map(factors, fix_factors),
                itemtype,
                ~ mirt(
                    d_mat,
                    .x, 
                    .y,
                    method = "EM", # might edit!
                    technical = list(NCYCLES = 200) # crank
                )
            ),
        log_lik = map_dbl(model_full, logLik),
        n_pars = map_int(model_full, ~ length(.@Internals$shortpars)),
        fscores = map(model_full, fscores)
    ) %>% 
    mutate(
        splits_with_log_lik = 
            map2(
                factors, 
                itemtype, 
                factors_itemtype_splits_df_to_splits_with_log_lik, 
                splits_d_mat,
                n_cycles = 200, # crank
                verbose = TRUE,
                the_method = "EM"
      )
  ) %>% 
    mutate(
        ll_person = 
          splits_with_log_lik %>% 
          map_dbl(~ exp(sum(.$log_lik_test) / nrow(d_mat))),
        ll_person_item = ll_person ^ (1 / ncol(d_mat))
  )

mirts %>% write_rds("02_mirts_1_and_2.rds")
```

# mirts 3 and 4

```{r}
mirts <- 
  tribble(
    ~factors,  ~itemtype,
        "3",      "2PL",
        "4",      "2PL"    
  ) %>% 
    mutate(
        model_full =
            map2(
                map(factors, fix_factors),
                itemtype,
                ~ mirt(
                    d_mat,
                    .x, 
                    .y,
                    method = "QMCEM", # might edit!
                    technical = list(NCYCLES = 200) # crank
                )
            ),
        log_lik = map_dbl(model_full, logLik),
        n_pars = map_int(model_full, ~ length(.@Internals$shortpars)),
        fscores = map(model_full, fscores)
    ) %>% 
    mutate(
        splits_with_log_lik = 
            map2(
                factors, 
                itemtype, 
                factors_itemtype_splits_df_to_splits_with_log_lik, 
                splits_d_mat,
                n_cycles = 200, # crank
                verbose = TRUE,
                the_method = "QMCEM"
      )
  ) %>% 
    mutate(
        ll_person = 
          splits_with_log_lik %>% 
          map_dbl(~ exp(sum(.$log_lik_test) / nrow(d_mat))),
        ll_person_item = ll_person ^ (1 / ncol(d_mat))
  )

mirts %>% write_rds("02_mirts_3_and_4.rds")
```

bifactors

```{r}
bifactors <- 
  tribble(
    ~factors,  ~itemtype,
    "bifact_all",  "2PL"
  ) %>% 
  mutate(
        model_full =
            map(
                map(factors, bifactor_to_specific),
                ~ bfactor(d_mat, ., technical = list(NCYCLES = 200)) # crank
            ),
        log_lik = map_dbl(model_full, logLik),
        n_pars = map_int(model_full, ~ length(.@Internals$shortpars)),
        fscores = map(model_full, fscores)
    ) %>% 
    mutate(
        splits_with_log_lik = 
            map(
                factors, 
                BBBfactors_splits_df_to_splits_with_log_lik, 
                splits_d_mat,
                n_cycles = 200, # crank
                verbose = FALSE
            )
  ) %>% 
    mutate(
        ll_person = 
          splits_with_log_lik %>% 
          map_dbl(~ exp(sum(.$log_lik_test) / nrow(d_mat))),
        ll_person_item = ll_person ^ (1 / ncol(d_mat))
  )

bifactors %>% write_rds("02_bifactors.rds")
```
