---
title: "9_analyzing_comparing_models_again"
output: html_document
---

```{r setup, include=FALSE}
# need to run top of 7 before fitting this model
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

models <- 
    bind_rows(
        read_rds("8_mirts.rds"),
        read_rds("8_bifactors.rds"),
        read_rds("17_mirts_just_4_factor.rds")
    ) %>% 
    rename(out_of_sample = ll_person_item) %>% 
    mutate(
        in_sample = exp(log_lik / nrow(d_mat))^(1/ncol(d_mat))
    )

models <- 
    models %>% 
    mutate(fscores_ml = map(model_full, ~ fscores(., "ML"))) %>% 
    select(factors:fscores, fscores_ml, everything())
```

```{r}
models %>%
    ggplot(aes(x = out_of_sample, y = in_sample, col = itemtype)) + 
    geom_point() +
    geom_hline(yintercept = mean(d_mat), lty = 2) + 
    geom_vline(xintercept = mean(d_mat), lty = 2) + 
    geom_abline(lty = 3)  +
    ggrepel::geom_label_repel(aes(label = factors)) +
    labs(title = "Model comparison")
```

# Trying to understand clumping of F1 for 3 factor 2PL

Not sure why but goes away when we switch to ML estimation

```{r}
items <- get_items(models$model_full[[3]])
high <- abs(items$a1) > 5

kids3f <- 
    get_kids(models$fscores[[3]]) %>% 
    left_join(rowSums(d_mat) %>% enframe() %>% rename(id = name, score = value)) %>% 
    left_join(rowSums(d_mat[ , high]) %>% enframe() %>% rename(id = name, score_high = value))

kids3f %>% filter(round(F1, 2) == -0.86) %>% View()
    

sort(items$a1)

test <- fscores(models$model_full[[3]], "ML")

tibble(
    ability = test[, 1],
    total_score = rowSums(d_mat)
) %>% 
    ggplot(aes(x = total_score, y = ability)) +
    geom_point()
```

# Ability plots

```{r}
# EAP
ggpairs(
    select(get_kids(models$fscores[[1]]), -id),
    aes(alpha = 0.01),
    title = "Rasch"
)

ggpairs(
    select(get_kids(models$fscores[[2]]), -id),
    aes(alpha = 0.01),
    title = "2 factor 2PL"
)

ggpairs(
    select(get_kids(models$fscores[[3]]), -id),
    aes(alpha = 0.01),
    title = "3 factor 2PL"
)

ggpairs(
    select(get_kids(models$fscores[[4]]), -id),
    aes(alpha = 0.01),
    title = "Bifactor"
)

# ML
ggpairs(
    select(get_kids(models$fscores_ml[[1]]), -id),
    aes(alpha = 0.01),
    title = "Rasch"
)

ggpairs(
    select(get_kids(models$fscores_ml[[2]]), -id),
    aes(alpha = 0.01),
    title = "2 factor 2PL"
)

ggpairs(
    select(get_kids(models$fscores_ml[[3]]), -id),
    aes(alpha = 0.01),
    title = "3 factor 2PL"
)

ggpairs(
    select(get_kids(models$fscores_ml[[4]]), -id),
    aes(alpha = 0.01),
    title = "Bifactor"
)
```

# Typical item

```{r}
models
items <- get_items(models$model_full[[2]])

items %>% 
    select(matches("a\\d")) %>% 
    gather(var, val) %>% 
    ggplot(aes(x = val)) +
    geom_histogram() +
    facet_wrap(~ var)

examples <- 
    items %>% 
    mutate(high_a1 = a1 < -3, high_a2 = a2 < -2, low_a1 = a1 > -0.5, low_a2 = a2 > -0.5) %>% 
    filter(high_a1 + high_a2 + low_a1 + low_a2 == 2) %>% 
    arrange(high_a1, high_a2, low_a1, low_a2) %>% 
    group_by(high_a1, high_a2, low_a1, low_a2) %>% 
    summarize(items = list(eng))

examples$items[[3]]
```


