---
title: "12_by_age"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mirt)
library(GGally)
library(rsample)
R.utils::sourceDirectory("~/Google_Drive/5_Projects/irt_comparison3/R")
theme_set(theme_classic(base_size = 14))
options(pillar.sigfig = 6)

d <- read_rds("data-clean/d.rds")

d_mat <- read_rds("data-clean/d_mat.rds")

milestones <-
    readxl::read_excel("data/norming2/0-48 milestones y abreviaciones (viejos vs nuevos).xlsx") %>%
    select(id = 1, area = 5, abbrev = 10, month = 6, eng = 4)

models <- 
    bind_rows(
        read_rds("11_mirts.rds"),
        # read_rds("11_bifactors.rds")
    ) %>% 
    rename(out_of_sample = ll_person_item) %>% 
    mutate(
        in_sample = exp(log_lik / nrow(d_mat))^(1/ncol(d_mat))
    )

# tidy it up in a better way
models <- 
    models %>% 
    mutate(
        oos = 
          splits_with_log_lik %>% map_dbl(~ sum(.$log_lik_test))
  ) %>% 
    select(factors, itemtype, in_log_lik = log_lik, in_p = in_sample, out_log_lik = oos, out_p = out_of_sample, model_full, fscores, splits_with_log_lik)
```

# Look at models from worst to best

```{r}
models %>% arrange(out_p)
```

# Prepare out

```{r}
split_model_to_oos <- function(split, model){
    tibble(
        id = row.names(testing(split)),
        oos = calc_log_lik_ghq2_student(model, testing(split))
    )
}

splits_with_ll_to_oos <- function(splits_with_log_lik) {
    splits_with_log_lik %>% 
        mutate(
            oos = map2(splits, model, split_model_to_oos)
        ) %>% 
        pull(oos) %>% 
        bind_rows() %>% 
        left_join(
            d %>% 
                group_by(id) %>% 
                summarize(age = age[1])
        )
}

out <- 
    models %>% 
    select(factors, itemtype, splits_with_log_lik) %>% 
    mutate(oos = splits_with_log_lik %>% map(splits_with_ll_to_oos))
```

What does age distribution look like

```{r}
d %>% 
    group_by(id) %>% 
    summarize(age = age[1]) %>% 
    ggplot(aes(x = age)) +
    geom_histogram(binwidth = 5) +
    labs(title = "histogram of the 1981 kids' ages")
```

Plot performance

```{r}
out %>% 
    select(-splits_with_log_lik) %>% 
    unnest() %>% 
    mutate(oos = log(oos)) %>% 
    mutate(type = paste0(itemtype, " ", factors, " factors")) %>% 
    mutate(type = factor(type, levels = c("Rasch 1 factors", "2PL 1 factors", "2PL 2 factors", "2PL 3 factors"))) %>% 
    ggplot(aes(x = age, y = oos, fill = type)) +
    geom_point(alpha = 0.1, color = "black") +
    geom_smooth(se = FALSE) +
    facet_wrap(~ type, ncol = 4) +
    guides(fill = FALSE) +
    labs(y = "student's log likelihood",
         title = "all models do worst in middle of age distribution",
         subtitle = "each data point is a student — each model run with 6-fold cv")
```

Compare two models

```{r}
# compare values
out$oos[[1]] %>% 
    left_join(out$oos[[2]] %>% rename(oos2 = oos)) %>% 
    mutate(oos = log(oos), oos2 = log(oos2)) %>% 
    ggplot(aes(x = oos, y = oos2, color = age)) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    labs(x = "student's log lik from Rasch 1 factor model", y = "student's log lik from 2PL 1 factor model",
         title = "where does moving from 1pl to 2pl help?")

# how much better at each age
out$oos[[1]] %>% 
    left_join(out$oos[[2]] %>% rename(oos2 = oos)) %>% 
    mutate(oos2 = log(oos2), oos = log(oos)) %>% 
    mutate(diff = oos2 - oos) %>% 
    ggplot(aes(x = age, y = diff)) +
    geom_point(alpha = 0.1) +
    geom_hline(yintercept = 0, color = "red") +
    labs(y = "student's 2pl 1 factor log lik - 1pl 1 factor log lik")

# look at mean instead
mean_each_age <- 
    out$oos[[1]] %>% 
    left_join(out$oos[[2]] %>% rename(oos2 = oos)) %>% 
    mutate(oos2 = log(oos2), oos = log(oos)) %>% 
    mutate(diff = oos2 - oos) %>% 
    group_by(age) %>% 
    summarize(mean_diff = mean(diff), n = n())

mean_each_age %>% 
    ggplot(aes(x = age, y = mean_diff, size = n)) +
    geom_point(alpha = 0.5) +
    labs(y = "mean difference in log lik for that age")
```

```{r}
# compare values
out$oos[[2]] %>% 
    left_join(out$oos[[3]] %>% rename(oos2 = oos)) %>% 
    mutate(oos = log(oos), oos2 = log(oos2)) %>% 
    ggplot(aes(x = oos, y = oos2, color = age)) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    labs(x = "student's log lik from 2PL 1 factor model", y = "student's log lik from 2PL 2 factors model",
         title = "where does adding another factor to 2pl model help?")

# how much better at each age
out$oos[[2]] %>% 
    left_join(out$oos[[3]] %>% rename(oos2 = oos)) %>% 
    mutate(oos2 = log(oos2), oos = log(oos)) %>% 
    mutate(diff = oos2 - oos) %>% 
    ggplot(aes(x = age, y = diff)) +
    geom_point(alpha = 0.1) +
    geom_hline(yintercept = 0, color = "red") +
    labs(y = "student's 2pl 2 factor log lik - 2pl 1 factor log lik")

# look at mean instead
mean_each_age <- 
    out$oos[[2]] %>% 
    left_join(out$oos[[3]] %>% rename(oos2 = oos)) %>% 
    mutate(oos2 = log(oos2), oos = log(oos)) %>% 
    mutate(diff = oos2 - oos) %>% 
    group_by(age) %>% 
    summarize(mean_diff = mean(diff), n = n())

mean_each_age %>% 
    ggplot(aes(x = age, y = mean_diff, size = n)) +
    geom_point(alpha = 0.5) +
    labs(y = "mean difference", title = "How much better is 2F than 1F at each age?")

mean_each_age <- 
    out$oos[[3]] %>% 
    left_join(out$oos[[4]] %>% rename(oos2 = oos)) %>% 
    mutate(oos2 = log(oos2), oos = log(oos)) %>% 
    mutate(diff = oos2 - oos) %>% 
    group_by(age) %>% 
    summarize(mean_diff = mean(diff), n = n())

mean_each_age %>% 
    ggplot(aes(x = age, y = mean_diff, size = n)) +
    geom_point(alpha = 0.5) +
    labs(y = "mean difference", title = "How much better is 3F than 2F at each age?")
```

Compare two models

```{r}
# compare values
out$oos[[1]] %>% 
    left_join(out$oos[[4]] %>% rename(oos2 = oos)) %>% 
    mutate(oos = log(oos), oos2 = log(oos2)) %>% 
    ggplot(aes(x = oos, y = oos2, color = age)) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    labs(x = "student's log lik from Rasch 1 factor model", y = "student's log lik from 2PL 1 factor model",
         title = "where does moving from 1pl to 2pl help?")

# how much better at each age
out$oos[[1]] %>% 
    left_join(out$oos[[4]] %>% rename(oos2 = oos)) %>% 
    mutate(oos2 = log(oos2), oos = log(oos)) %>% 
    mutate(diff = oos2 - oos) %>% 
    geom_point(alpha = 0.1) +
    ggplot(aes(x = age, y = diff)) +
    geom_hline(yintercept = 0, color = "red") +
    labs(y = "student's 2pl 1 factor log lik - 1pl 1 factor log lik")

# look at mean instead
mean_each_age <- 
    out$oos[[2]] %>% 
    left_join(out$oos[[4]] %>% rename(oos2 = oos)) %>% 
    mutate(oos2 = log(oos2), oos = log(oos)) %>% 
    mutate(diff = oos2 - oos) %>% 
    group_by(age) %>% 
    summarize(mean_diff = mean(diff), sum_diff = sum(diff), n = n())

mean_each_age %>% 
    ggplot(aes(x = age, y = mean_diff, size = n)) +
    geom_point(alpha = 0.5) +
    labs(y = "mean difference")

mean_each_age %>% 
    ggplot(aes(x = age, y = sum_diff, size = n)) +
    geom_point(alpha = 0.5) +
    labs(y = "sum difference")
```
