---
title: "14_analyze_splits_by_age"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mirt)
mirtCluster()
library(rsample)
theme_set(theme_classic(base_size = 14))
options(pillar.sigfig = 6)

R.utils::sourceDirectory("~/Google_Drive/5_Projects/irt_comparison3/R")
source("6_functions.R")

areas <- read_rds("data-clean/areas.rds")
d <- read_rds("data-clean/d.rds")
d_mat <- read_rds("data-clean/d_mat.rds")
item_area <- areas$area[match(colnames(d_mat), areas$paste)]

splits_by_age <- read_rds("13_splits_by_age.rds")
```

```{r}
a <- splits_by_age$models[[1]]

a$splits_with_log_lik[[1]]

add_lltest <- function(a){
  a %>% 
  mutate(
    log_lik_test = 
      splits_with_log_lik %>% 
      map_dbl(~ sum(.$log_lik_test))
  )
}

b <- splits_by_age %>% 
  mutate(models2 = models %>% map(add_lltest))

tibble(
  years = c("2-12 months", "13-24 months", "25-36 months", "37+ months")
) %>% 
  mutate(
    kids = splits_by_age$d_mat_filter %>% map_int(nrow),
    items = splits_by_age$d_mat_filter %>% map_int(ncol),
    m  = b$models2
  ) %>% 
  unnest() %>% 
  select(years, kids, items, factors, itemtype, log_lik, log_lik_test) %>% 
  mutate(var = as_factor(paste0(years, " ", kids, " kids", " ", items, " items"))) %>% 
  filter(itemtype == "2PL") %>% 
  ggplot(aes(x = factors, y = log_lik_test)) +
  geom_point() +
  geom_line(aes(group = years)) +
  facet_wrap(~ var, ncol = 1, scales = "free") +
  labs(title = "Vary # of factors for 2PL and compare fit for each age range", subtitle = "be careful: simpler models tend to fit better at small sample sizes", y = "out-of-sample log likelihood")
```

mike wants to see splits 

```{r}
splits_by_age$models[[2]]

a <- splits_by_age %>% 
  select(years, models) %>% 
  mutate(
    years = c("2-12 months", "13-24 months", "25-36 months", "37+ months"),
    model = models %>% map(~ .$model_full[[4]]),
    coefs = model %>% map(~ coef(., simplify = TRUE)$items)
  ) %>% 
  select(years, coefs) %>% 
  mutate(coefs = coefs %>% map(~ mutate(as_tibble(.), item = row.names(.)))) %>% 
  unnest()

a %>% 
  group_by(years) %>% 
  summarize(n = sum(a3^2))

a %>% 
  #filter(years %in% c("2-12 months", "37+ months")) %>% 
  group_by(item) %>% 
  #filter(n() == 2) %>% 
  ungroup() %>% 
  mutate(years = factor(years, levels = c("2-12 months", "13-24 months", "25-36 months", "37+ months"))) %>% 
  left_join(areas, by = c("item" = "paste")) %>% 
  select(years, area, a1:a3) %>% 
  mutate(a1 = -a1, a2 = -a2) %>% 
  gather(var, val, -area, -years) %>% 
  ggplot(aes(x = val, fill = area)) +
  ggridges::geom_density_line(alpha = 0.5) +
  facet_grid(years ~ var) +
  labs(
        x = "factor loading",
        y = "density",
        subtitle = "each model (e.g. for kids 2-12 months) is fit independently"
  )

```



```{r}
splits_by_age$models[[1]]

splits_by_age %>% 
  select(years, models) %>% 
  mutate(
    years = c("2-12 months", "13-24 months", "25-36 months", "37+ months"),
    years = factor(years, levels = c("2-12 months", "13-24 months", "25-36 months", "37+ months")),
    model = models %>% map(~ .$model_full[[4]]),
    prop_var = model %>% map(get_prop_var)
  ) %>% 
  select(years, prop_var) %>% 
  unnest() %>% 
  arrange(years, desc(prop_var)) %>% 
  mutate(factor = rep(1:3, 4)) %>% 
  filter(factor == 3) %>% 
  ggplot(aes(x = years, y = prop_var)) +
  geom_col() +
  labs(
    y = "Proportion variance explained by 3rd factor",
    subtitle = "How much better does model for each age group get when moving from 2F to 3F?"
  )

splits_by_age$models[[2]]$model_full[[4]] %>% get_prop_var()

# this is weird that when i don't rotate i get reversal
summary(splits_by_age$models[[2]]$model_full[[4]], rotate = "none")

# but when i do rotate i don't get that reversal
summary(splits_by_age$models[[2]]$model_full[[4]])

object <- splits_by_age$models[[2]]$model_full[[4]]

get_prop_var <- function(object){
  F <- object@Fit$F
  SS <- apply(F^2, 2, sum)
  SS / nrow(F)
}
```



```{r}
splits_by_age %>% 
  select(years, models) %>% 
  mutate(
    years = c("2-12 months", "13-24 months", "25-36 months", "37+ months"),
    years = factor(years, levels = c("2-12 months", "13-24 months", "25-36 months", "37+ months")),
    model = models %>% map(~ .$model_full[[3]]),
    prop_var = model %>% map(get_prop_var)
  ) %>% 
  select(years, prop_var) %>% 
  unnest() %>% 
  mutate(factor = rep(1:2, 4), factor = factor(factor)) %>% 
  ggplot(aes(x = factor, y = prop_var)) +
  geom_col() +
  facet_wrap(~ years, ncol = 2) +
  labs(
    y = "Proportion variance",
    subtitle = "2F model for each age partition"
  )
```

```{r}
splits_by_age %>% 
  select(years, models) %>% 
  mutate(
    years = c("2-12 months", "13-24 months", "25-36 months", "37+ months"),
    years = factor(years, levels = c("2-12 months", "13-24 months", "25-36 months", "37+ months")),
    model = models %>% map(~ .$model_full[[4]]),
    prop_var = model %>% map(get_prop_var)
  ) %>% 
  select(years, prop_var) %>% 
  unnest() %>% 
  arrange(years, desc(prop_var)) %>% 
  mutate(factor = rep(1:3, 4), factor = factor(factor)) %>% 
  ggplot(aes(x = factor, y = prop_var)) +
  geom_col() +
  facet_wrap(~ years, ncol = 2) +
  labs(
    y = "Proportion variance",
    subtitle = "3F model for each age partition"
  )

splits_by_age$models[[2]]$model_full[[4]] %>% 
  summary(rotate = "none")
```



```{r}
my_data <- 
  splits_by_age %>% 
  select(years, models) %>% 
  mutate(
    years = c("2-12 months", "13-24 months", "25-36 months", "37+ months"),
    years = factor(years, levels = c("2-12 months", "13-24 months", "25-36 months", "37+ months")),
    model = models %>% map(~ .$model_full[[4]]),
    prop_var = model %>% map(get_prop_var)
  ) %>% 
  select(years, prop_var) %>% 
  unnest() %>% 
  arrange(years, desc(prop_var)) %>% 
  mutate(factor = rep(1:3, 4), factor = factor(factor))

my_data %>% 
  rename(`age bucket` = years) %>% 
  ggplot(aes(x = factor, y = prop_var, color = `age bucket`)) +
  geom_point(size = 3) +
  geom_line(aes(group = `age bucket`)) +
  labs(
    y = "Proportion variance",
    subtitle = "3F model for each age partition"
  ) +
  scale_y_continuous(labels = scales::percent) +
  scale_color_viridis_d()

```

