---
title: "15_run_more_models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mirt)
mirtCluster()
library(rsample)
theme_set(theme_classic(base_size = 14))
options(pillar.sigfig = 6)

R.utils::sourceDirectory("~/Google_Drive/5_Projects/irt_comparison3/R")
source("15_functions.R")

areas <- read_rds("data-clean/areas.rds")
d_mat <- read_rds("data-clean/d_mat.rds")
item_area <- areas$area[match(colnames(d_mat), areas$paste)]

splits_d_mat <- vfold_cv(d_mat, v = 6) # crank
```

full models

```{r}
mirts <- 
  tribble(
    ~factors,  ~itemtype,
        "4",      "2PL",
        "3",      "2PL",
        "2",      "2PL",
  ) %>% 
    mutate(
        model_full =
            map2(
                map(factors, fix_factors),
                itemtype,
                ~ mirt(
                    d_mat,
                    .x, 
                    .y,
                    method = "QMCEM",
                    # quadpts = 6, (best to use built in formula — perhaps?)
                    technical = list(NCYCLES = 300) # crank
                )
            )
    )
```

dive into full models

```{r}
mirts2 <-
  mirts %>% 
  mutate(
    log_lik = map_dbl(model_full, logLik),
    n_pars = map_int(model_full, ~ length(.@Internals$shortpars)),
    fscores = map(model_full, fscores, QMC = TRUE)
  )
```

cross validate

```{r}
# for when things crash: mirts2 <- read_rds("15_mirts2.rds")

mirts3 <- 
  mirts2 %>% 
    mutate(
        splits_with_log_lik = 
            map2(
                factors, 
                itemtype, 
                factors_itemtype_splits_df_to_splits_with_log_lik, 
                splits_d_mat,
                n_cycles = 300, # crank
                verbose = TRUE,
                method = "QMCEM"
      )
  ) %>% 
    mutate(
        ll_person = 
          splits_with_log_lik %>% 
          map_dbl(~ exp(sum(.$log_lik_test) / nrow(d_mat))),
        ll_person_item = ll_person ^ (1 / ncol(d_mat))
  )
```

above wasn't working so let's use our magical purrrplus

```{r}
library(purrrplus)

function_just_takes_factors_and_itemtype <- function(factors, itemtype){
  factors_itemtype_splits_df_to_splits_with_log_lik(
    factors = factors,
    itemtype = itemtype,
    splits_df = splits_d_mat,
    n_cycles = 100,
    verbose = TRUE,
    method = "QMCEM"
  )
}

what <- pmap_safely(mirts2, function_just_takes_factors_and_itemtype)
```

that wasn't working so let's breakdown even more

```{r}
factors <- 4
itemtype <- "2PL"
splits_df <- splits_d_mat
n_cycles <- 100
verbose <- TRUE
method <- "QMCEM"

# the function we're running

factors_itemtype_splits_df_to_splits_with_log_lik

splits_df %>%
            mutate(
                model =
                    splits %>%
                    map(
                        ~ list(
                            data = training(.),
                            model = fix_factors(factors),
                            itemtype = itemtype,
                            TOL = 0.0002, # could crank
                            technical = list(theta_lim = c(-6, 6), NCYCLES = n_cycles),
                            verbose = verbose,
                            method = method
                        )
                    ) %>%
                    map(~ do.call(mirt, .))
                )

# let's run it manually for the first one

period <- splits_df$splits[[1]]

first <- 
  mirt(
    data = training(period), 
    model = 4, 
    itemtype, 
    TOL = 0.0002, 
    technical = list(theta_lim = c(-6, 6), NCYCLES = n_cycles),
    verbose = TRUE,
    method = "EM"
)

# great i have the error!!
calc_log_lik_ghq2(first, testing(period))
```



output

```{r}
mirts2 %>% write_rds("15_mirts2.rds")
```
