---
title: "18_comparing_4_factor_splits_by_age"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
d_mat <- read_rds("data-clean/d_mat.rds")
mirts4 <- read_rds("17_mirts_just_4_factor.rds")
mirts <- read_rds("11_mirts.rds")

all <- 
    bind_rows(
        mirts,
        mirts4
    ) %>% 
    rename(out_of_sample = ll_person_item) %>% 
    mutate(
        in_sample = exp(log_lik / nrow(d_mat))^(1/ncol(d_mat))
    ) %>% 
    mutate(
        oos = 
          splits_with_log_lik %>% map_dbl(~ sum(.$log_lik_test))
  ) %>% 
    select(
        factors, itemtype, in_log_lik = log_lik, in_p = in_sample, 
        out_log_lik = oos, out_p = out_of_sample, model_full, fscores, splits_with_log_lik)
```

```{r}
all %>% 
    filter(itemtype == "2PL") %>% 
    select(factors, in_p, out_p) %>% 
    rename(in_sample = in_p, out_of_sample = out_p) %>% 
    gather(var, val, -factors) %>% 
    ggplot(aes(x = factors, y = val, color = var)) +
    geom_point() +
    geom_line(aes(group = var)) +
    labs(
        x = "Factors",
        y = "Normalized likelihood",
        color = "",
        title = "3F model fits all of data best"
    )
```


