---
title: "2_ben_comparing_to_mike_results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_classic(base_size = 14))
library(mirt)
```

# Prepare data

```{r}
# read in
fix_names <- function(x) ifelse(x == "", paste0("X__", 1:length(x) - 1), x)

d_raw <- 
  readxl::read_xlsx(
    "data/norming2/Kinedu Norming Survey Raw Data - May 15 2018.xlsx", 
    .name_repair = fix_names
  )

# prepare irt matrix
d <- 
  d_raw %>%
  mutate(age = as.numeric(X__422), 
         gestation = as.numeric(X__3),
         kinder = as.numeric(X__4),
         diagnosis = as.numeric(X__1), 
         id = `Nombre variable`) %>%
  slice(4:n()) %>% # drop two top label rows. 
  select(-starts_with("X"), -`Nombre variable`) %>%
  gather(code, response, abs_183:color_679) %>%
  mutate(code = str_replace(code, "^d_","d"),
         code = str_replace(code, "^e_",""),
         code2 = code) %>%
  separate(code2, into = c("category","number")) %>%
  select(-number) %>%
  mutate(response = as.numeric(response)) %>% 
  filter(age != 0) # DROP AGE 0

d_wide <- d %>%
  select(id, code, response) %>%
  spread(code, response)
  
d_mat <- d_wide %>%
  select(-id) %>% 
  data.frame %>%
  data.matrix

colnames(d_mat) <- sort(unique(d$code))
rownames(d_mat) <- d_wide$id

# lots of items / students is relatively high
dim(d_mat)
```

# Compare my model to Mike's

```{r}
mod_4pl_ben <- mirt(d_mat, 1, itemtype='4PL', verbose=FALSE)

load("data-emailed-from-mike/norming2_mod_4pl.rds")

all(
    coef(mod_4pl_ben, simplify = TRUE)$items[ , "a1"] == 
    coef(mod_4pl, simplify = TRUE)$items[ , "a1"]
)

M2(mod_4pl_ben)

fscores_4pl_ben <- 
    tibble(
        id = rownames(d_mat), 
        ability = fscores(mod_4pl_ben, method = "MAP")[ , 1]
    )

fscores_4pl$id == fscores_4pl_ben$id

fscores_4pl$ability == fscores_4pl_ben$ability

plot(fscores_4pl$ability, fscores_4pl_ben$ability)
```

```{r}
mod_1pl_ben <- mirt(d_mat, 1, itemtype='Rasch', verbose=FALSE)

mod_2pl_ben <- mirt(d_mat, 1, itemtype='2PL', verbose=FALSE)

mod_3pl_ben <- mirt(d_mat, 1, itemtype='3PL', verbose=FALSE)

anova(mod_3pl_ben, mod_4pl)

anova(mod_1pl_ben, mod_4pl)
```

