---
title: "3_par_prior"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_classic(base_size = 14))
library(mirt)
```

# Prepare data

```{r}
# read in
fix_names <- function(x) ifelse(x == "", paste0("X__", 1:length(x) - 1), x)

d_raw <- 
  readxl::read_xlsx(
    "data/norming2/Kinedu Norming Survey Raw Data - May 15 2018.xlsx", 
    .name_repair = fix_names
  )

# prepare irt matrix
d <- 
  d_raw %>%
  mutate(age = as.numeric(X__422), 
         gestation = as.numeric(X__3),
         kinder = as.numeric(X__4),
         diagnosis = as.numeric(X__1), 
         id = `Nombre variable`) %>%
  slice(4:n()) %>% # drop two top label rows. 
  select(-starts_with("X"), -`Nombre variable`) %>%
  gather(code, response, abs_183:color_679) %>%
  mutate(code = str_replace(code, "^d_","d"),
         code = str_replace(code, "^e_",""),
         code2 = code) %>%
  separate(code2, into = c("category","number")) %>%
  select(-number) %>%
  mutate(response = as.numeric(response)) %>% 
  filter(age != 0) # DROP AGE 0

d_wide <- d %>%
  select(id, code, response) %>%
  spread(code, response)
  
d_mat <- d_wide %>%
  select(-id) %>% 
  data.frame %>%
  data.matrix

colnames(d_mat) <- sort(unique(d$code))
rownames(d_mat) <- d_wide$id

# lots of items / students is relatively high
dim(d_mat)
```

# Compare my model to Mike's

```{r}
mod_3pl <- mirt(d_mat, 1, itemtype='3PL', verbose=FALSE)
mod_4pl <- mirt(d_mat, 1, itemtype='4PL', verbose=FALSE)

vals <- mirt(d_mat, 1, itemtype='4PL', verbose=FALSE, pars = 'values')

mod_4pl_expbeta <- 
    mirt(
        d_mat, 1, itemtype='4PL', verbose=FALSE, 
        parprior = list(c(which(vals$name == "u"), 'expbeta', 20, 2))
    )

mod_4pl_rnorm <- 
    mirt(
        d_mat, 1, itemtype='4PL', verbose=FALSE, 
        parprior = 
            list(
                c(which(vals$name == "u"), 'norm', 0.9, 0.05),
                c(which(vals$name == "g"), 'norm', 0.2, 0.05)
            )
    )

mod_3pl_2 <- mirt(d_mat, 2, itemtype='3PL', verbose=TRUE)

coef(mod_3pl_2)

coef(mod_4pl_rnorm)

anova(mod_3pl_2, mod_3pl)

dim(d_mat)

mod_2pl_2 <- mirt(d_mat, 2, itemtype='2PL', verbose=TRUE)

mod_2pl_2b <- mirt(d_mat, 2, itemtype='2PL', verbose=TRUE, method = "QMCEM")

anova(mod_3pl_2, mod_2pl_2)

plot(mod_3pl_2)

itemplot(mod_3pl_2, 20)

coef(mod_3pl_2)

anova(mod_2pl_2b, mod_2pl_2)

which(row.names(coef(mod_3pl, simplify = TRUE)$items) == "color_666")

coef(mod_3pl)

plot(mod_3pl_2, type = "item")

itemplot(mod_3pl, 51)


```
