---
title: "4_moving_ahead_with_3pl"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_classic(base_size = 14))
library(mirt)
```

# Prepare data

```{r}
# read in
fix_names <- function(x) ifelse(x == "", paste0("X__", 1:length(x) - 1), x)

d_raw <- 
  readxl::read_xlsx(
    "data/norming2/Kinedu Norming Survey Raw Data - May 15 2018.xlsx", 
    .name_repair = fix_names
  )

# prepare irt matrix
d <- 
  d_raw %>%
  mutate(age = as.numeric(X__422), 
         gestation = as.numeric(X__3),
         kinder = as.numeric(X__4),
         diagnosis = as.numeric(X__1), 
         id = `Nombre variable`) %>%
  slice(4:n()) %>% # drop two top label rows. 
  select(-starts_with("X"), -`Nombre variable`) %>%
  gather(code, response, abs_183:color_679) %>%
  mutate(code = str_replace(code, "^d_","d"),
         code = str_replace(code, "^e_",""),
         code2 = code) %>%
  separate(code2, into = c("category","number")) %>%
  select(-number) %>%
  mutate(response = as.numeric(response)) %>% 
  filter(age != 0) # DROP AGE 0

d_wide <- d %>%
  select(id, code, response) %>%
  spread(code, response)
  
d_mat <- d_wide %>%
  select(-id) %>% 
  data.frame %>%
  data.matrix

colnames(d_mat) <- sort(unique(d$code))
rownames(d_mat) <- d_wide$id

# lots of items / students is relatively high
dim(d_mat)
```

Helper functions

```{r}
get_item_pars <- function(model){
    coef(model, simplify = TRUE)$items %>% 
        as.data.frame() %>% 
        mutate(item = row.names(.)) %>% 
        as_tibble() %>% 
        select(-u)
}

graph_item_pars <- function(item_pars){
    item_pars %>% 
        select(-item) %>% 
        gather(var, val) %>% 
        ggplot(aes(x = val)) +
        geom_histogram() +
        facet_wrap(~ var, ncol = 1, scales = "free")
}
```

# Fitting models

## 1 factor

```{r}
# fit model
mod_3pl_1 <- mirt(d_mat, 1, itemtype = "3PL", verbose = FALSE)

# get items
items_3pl_1 <- get_item_pars(mod_3pl_1)

# graph items
graph_item_pars(items_3pl_1)

# look at problematic items
items_3pl_1 %>% filter(a1 < 0.25 | a1 > 5) %>% arrange(desc(abs(a1)))

d_mat[ , c("conver_617", "babbling _589", "conver_656")] %>% 
    colMeans()

d_mat[ , c("conver_617", "babbling _589", "conver_656")] %>%
    as_tibble() %>% 
    group_by_all() %>% 
    summarize(n = n())
```

## 1 factor w/ prior

```{r}
vals <- mirt(d_mat, 1, itemtype='3PL', verbose=FALSE, pars = 'values')

mod_3pl_1_shrunk <- 
    mirt(
        d_mat, 1, itemtype='3PL', verbose=TRUE, 
        parprior = 
            list(
                c(which(vals$name == "a1"), 'norm', 1, 1)
            )
    )

# get items
items_3pl_1_shrunk <- get_item_pars(mod_3pl_1_shrunk)

# graph items
graph_item_pars(items_3pl_1_shrunk)
```

## 2 factors

```{r}
mod_3pl_2 <- mirt(d_mat, 2, itemtype = "3PL", verbose = TRUE)
```

## 2 factors with prior

```{r}
vals2 <- mirt(d_mat, 2, itemtype='3PL', verbose=FALSE, pars = 'values')

mod_3pl_2_shrunk <- 
    mirt(
        d_mat, 2, itemtype = "3PL", verbose = TRUE,
        parprior = 
            list(
                c(which(vals2$name == "a1"), 'norm', 1, 1),
                c(which(vals2$name == "a2"), 'norm', 1, 1)
            )
    )

save.image("4_models.Rdata")
```

```{r}
mod_3pl_1 %>% get_item_pars() %>% graph_item_pars()

mod_3pl_1_shrunk %>% get_item_pars() %>% graph_item_pars()

mod_3pl_2 %>% get_item_pars() %>% graph_item_pars()

mod_3pl_2_shrunk %>% get_item_pars() %>% graph_item_pars()


list(mod_3pl_1, mod_3pl_1_shrunk, mod_3pl_2, mod_3pl_2_shrunk) %>% map(logLik)
```



# Compare models


```{r}
anova(mod_3pl_1, mod_3pl_1_shrunk)
```



