---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
set.seed(123)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(mirt)
mirtCluster()
library(rsample)

source(here("R", "calc_log_lik_ghq2_student.R"))
source(here("R", "fix_factors.R"))
source(here("R", "factors_itemtype_splits_df_to_splits_with_log_lik.R"))
```

load then filter by age

```{r}
responses_long <- read_rds(here("data-clean/responses_long.rds"))
responses_wide <- read_rds(here("data-clean/responses_wide.rds"))

by_age <-
	responses_long %>%
	group_by(id) %>%
	summarize(
		age = age[1],
		response = sum(response)
	) %>%
	filter(age > 1)

responses_wide <- responses_wide %>% filter(id %in% by_age$id)
responses_long <- responses_long %>% filter(age > 1)

responses_matrix <- 
	responses_wide %>% 
	select(-id) %>% 
	as.matrix()
```

```{r}
splits_response_matrix <- vfold_cv(responses_matrix, v = 6)
```

# mirts

```{r}
mirts <- 
  tribble(
    ~factors,  ~itemtype,
        "1",      "Rasch",
        "1",      "2PL",
        "2",      "2PL",
        "3",      "2PL",
        "4",      "2PL",
        "5",      "2PL"
  ) %>% 
    mutate(
        model_full =
            map2(
                map(factors, fix_factors),
                itemtype,
                ~ mirt(
                    d_mat,
                    .x, 
                    .y,
                    method = "EM", 
                    technical = list(NCYCLES = 500)
                )
            ),
        log_lik = map_dbl(model_full, logLik),
        n_pars = map_int(model_full, ~ length(.@Internals$shortpars)),
        fscores = map(model_full, fscores)
    ) %>% 
    mutate(
        splits_with_log_lik = 
            map2(
                factors, 
                itemtype, 
                factors_itemtype_splits_df_to_splits_with_log_lik, 
                splits_d_mat,
                n_cycles = 500, 
                verbose = TRUE,
                the_method = "EM"
      )
  ) %>% 
    mutate(
        ll_person = 
          splits_with_log_lik %>% 
          map_dbl(~ exp(sum(.$log_lik_test) / nrow(d_mat))),
        ll_person_item = ll_person ^ (1 / ncol(d_mat))
  )
mirts %>% write_rds("02_mirts_2_add_5.rds")
```

# bifactors

```{r}
bifactors <- 
  tribble(
    ~factors,  ~itemtype,
    "bifact_all",  "2PL"
  ) %>% 
  mutate(
        model_full =
            map(
                map(factors, bifactor_to_specific),
                ~ bfactor(d_mat, ., technical = list(NCYCLES = 400)) # crank
            ),
        log_lik = map_dbl(model_full, logLik),
        n_pars = map_int(model_full, ~ length(.@Internals$shortpars)),
        fscores = map(model_full, fscores)
    ) %>% 
    mutate(
        splits_with_log_lik = 
            map(
                factors, 
                BBBfactors_splits_df_to_splits_with_log_lik, 
                splits_d_mat,
                n_cycles = 400, # crank
                verbose = FALSE
            )
  ) %>% 
    mutate(
        ll_person = 
          splits_with_log_lik %>% 
          map_dbl(~ exp(sum(.$log_lik_test) / nrow(d_mat))),
        ll_person_item = ll_person ^ (1 / ncol(d_mat))
  )

bifactors %>% write_rds("02_bifactors_2.rds")
```
